version: "3.8"

services:
  backend:
    image: chaklams072/template-backend
    platform: linux/amd64
    container_name: dev-django
    command: gunicorn -b 0.0.0.0:8000 api.wsgi:application
    env_file:
      - ./.env.dev
    volumes:
      - static:/src/app/static
      - media:/src/app/media
    depends_on:
      - db

  frontend:
    image: chaklams072/template-frontend
    platform: linux/amd64
    container_name: dev-nuxt
    command: yarn dev
    # volumes:
      # - ./frontend:/root/project
      # - node_modules-frontend:/root/project/node_modules
      # - vscode-frontend:/root/.vscode-server
    depends_on:
      - backend
      - fastapi

  fastapi:
    image: chaklams072/fastapi
    platform: linux/amd64
    container_name: dev-fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --root-path /fastapi
    env_file:
      - ./.env.dev

  db:
    image: postgres:16.1-alpine
    container_name: dev-db
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    env_file: ./.env.dev
    ports:
      - "5050:5050"
    depends_on:
      - db

  nginx:
    image: chaklams072/template-reverseproxy
    platform: linux/amd64
    container_name: dev-nginx
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/src/app/static
      - media:/src/app/media
    depends_on:
      - backend
      - frontend
      - db
      - fastapi

volumes:
  postgres_data:
  media:
  static: