version: "3.8"

services:

  frontend:
    image: chaklams072/template-frontend
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64

    volumes:
      - .:/root/project
      - /root/project/node_modules
      - .vscode-server/frontend:/root/.vscode-server
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000