version: "3.8"

services:
  django:
    build: ./backend
    platform: linux/amd64
    image: chaklams072/django
    container_name: dev-django
    command: gunicorn -b 0.0.0.0:8000 api.wsgi:application
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/:/src/app
      - static:/src/app/static
      - media:/src/app/media
      - vscode-django:/root/.vscode-server
    depends_on:
      - db

  frontend:
    image: chaklams072/template-frontend
    build:
      context: ./frontend
      dockerfile: nuxt.Dockerfile
    platform: linux/amd64
    command: yarn dev
    # volumes:
      # - ./frontend:/root/project
      # - node_modules-frontend:/root/project/node_modules
      # - vscode-frontend:/root/.vscode-server
    depends_on:
      - django
      - fastapi

  # react:
  #   build: ./frontend
  #   platform: linux/amd64
  #   image: chaklams072/react
  #   container_name: dev-react
  #   command: npm run dev
  #   env_file:
  #     - ./.env.dev
  #   tty: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - ./frontend/:/src/app
  #     - node_modules:/src/app/node_modules
  #     - vscode-react:/root/.vscode-server
  #   depends_on:
  #     - django
  #     - fastapi

  fastapi:
    build: ./model
    platform: linux/amd64
    image: chaklams072/fastapi
    container_name: dev-fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --root-path /fastapi
    env_file:
      - ./.env.dev
    volumes:
      - ./model/:/src/app
      - vscode-fastapi:/root/.vscode-server

  db:
    image: postgres:16.1-alpine
    container_name: dev-db
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    env_file: ./.env.dev
    ports:
      - "5050:5050"
    depends_on:
      - db

  nginx:
    build: ./nginx
    platform: linux/amd64
    image: chaklams072/nginx
    container_name: dev-nginx
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/src/app/static
      - media:/src/app/media
    depends_on:
      - django
      - frontend
      - db
      - fastapi

volumes:
  node_modules:
  postgres_data:
  media:
  static:
  vscode-django:
  vscode-frontend:
  node_modules-frontend:
  vscode-fastapi:
