version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: nuxt.Dockerfile
    volumes:
      - ./nuxt:/root/project
      - node_modules-frontend:/root/project/node_modules
      - vscode-frontend:/root/.vscode-server

volumes:
  vscode-frontend:
  node_modules-frontend:
