version: "3.8"

services:
  django:
    build: ./backend
    container_name: dev-django
    command: gunicorn -b 0.0.0.0:8000 api.wsgi:application
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/:/src/app
      - static:/src/app/static
      - media:/src/app/media
    depends_on:
      - db

  react:
    build: ./frontend
    container_name: dev-react
    command: npm run dev
    env_file:
      - ./.env.dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/:/src/app
      - node_modules:/src/app/node_modules
    depends_on:
      - django
      - fastapi

  fastapi:
    build: ./model
    container_name: dev-fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --root-path /fastapi
    env_file:
      - ./.env.dev
    volumes:
      - ./model/:/src/app

  db:
    image: postgres:16.1-alpine
    container_name: dev-db
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    env_file: ./.env.dev
    ports:
      - "5050:5050"
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: dev-nginx
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/src/app/static
      - media:/src/app/media
    depends_on:
      - django
      - react
      - db
      - fastapi

volumes:
  node_modules:
  postgres_data:
  media:
  static:
