name: Deploy to Azure VM by pulling from docker hub

#uncomment these lines for it to work
# on:
#   push:
#     branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Create env file'
        run: |
          echo "${{ secrets.REACT_DJANGO_ENV_FILE }}" > .env.dev
      - name: Build the stack
        run: docker compose build
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the frontend image to Docker Hub
        run: docker push chaklams072/template-frontend
      - name: Push the backend image to Docker Hub
        run: docker push chaklams072/template-backend
      - name: Push the reverse proxy image to Docker Hub
        run: docker push chaklams072/template-reverseproxy
      - name: Push the react image to Fastapi Hub
        run: docker push chaklams072/fastapi
      - name: Pull the image to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd esg
            sudo docker compose pull
            sudo docker compose up -d
